const ONE_HOUR = 60;
export const TIMELINE_MINUTES_DIVISOR = 30;
export const TIMELINE_SECTION = ONE_HOUR / TIMELINE_MINUTES_DIVISOR;

export const ONE_MINUTE_IN_PIXELS = 8;
export const TIMELINE_ELEMENT_WIDTH_IN_PIXELS = (ONE_HOUR * ONE_MINUTE_IN_PIXELS) / TIMELINE_SECTION;